broker: WIS2BOX_BROKER_PUBLIC

# list of topics to subscribe to
topics:
    - 'origin/a/wis2/#'

# whether to verify data
verify_data: true

# whether to validate message against schema
validate_message: false
